PalletTown_NewHome2_MapScripts::
	.byte 0


OldMan::
# 3 "data/maps/PalletTown_NewHome2/scripts.pory"
	lock
# 4 "data/maps/PalletTown_NewHome2/scripts.pory"
	faceplayer
# 5 "data/maps/PalletTown_NewHome2/scripts.pory"
	msgbox OldMan_Text_0
# 6 "data/maps/PalletTown_NewHome2/scripts.pory"
	release
	end


LittleGirl::
# 11 "data/maps/PalletTown_NewHome2/scripts.pory"
	lock
# 12 "data/maps/PalletTown_NewHome2/scripts.pory"
	faceplayer
# 13 "data/maps/PalletTown_NewHome2/scripts.pory"
	msgbox LittleGirl_Text_0
# 14 "data/maps/PalletTown_NewHome2/scripts.pory"
	release
	end


OldMan_Text_0:
# 5 "data/maps/PalletTown_NewHome2/scripts.pory"
	.string "Many POKéMON in the region have\n"
	.string "differt types, stats, and moves to\l"
	.string "utilize. Enjoy discovering\l"
	.string "everything new in KANTO!$"

LittleGirl_Text_0:
# 13 "data/maps/PalletTown_NewHome2/scripts.pory"
	.string "My grandpa took me to the store to\n"
	.string "buy POKéMON Trading Cards, but\l"
	.string "they were all sold out...$"
