CeruleanCity_AlwaysBeenHere_MapScripts::
	.byte 0


AlwaysBeenHere::
# 3 "data/maps/CeruleanCity_AlwaysBeenHere/scripts.pory"
	lock
# 4 "data/maps/CeruleanCity_AlwaysBeenHere/scripts.pory"
	faceplayer
# 5 "data/maps/CeruleanCity_AlwaysBeenHere/scripts.pory"
	msgbox AlwaysBeenHere_Text_0
# 6 "data/maps/CeruleanCity_AlwaysBeenHere/scripts.pory"
	release
	end


AlwaysBeenHere_Text_0:
# 5 "data/maps/CeruleanCity_AlwaysBeenHere/scripts.pory"
	.string "This house here? Why, it's always\n"
	.string "been here! Who ever heard of a\l"
	.string "house without a door?$"
