PalletTown_NewHome1_2F_MapScripts::
	.byte 0


RetroGamer::
# 3 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	lock
# 4 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	faceplayer
# 5 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	msgbox RetroGamer_Text_0
# 6 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	release
	end


RetroGamerSister::
# 11 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	lock
# 12 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	faceplayer
# 13 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	msgbox RetroGamerSister_Text_0
# 14 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	release
	end


RetroGamer_Text_0:
# 5 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	.string "Modern games are loaded with\nbugs and microstransactions.\pThat's why I prefer retro gaming!$"

RetroGamerSister_Text_0:
# 13 "data/maps/PalletTown_NewHome1_2F/scripts.pory"
	.string "My brother only plays old and boring\nNintendo games.\pEveryone knows that gaming on\nthe PC is the best!$"
