gText_WantMeToTeachMove::
    .string "I'm a POKÉMON MOVE RELEARNER.\p"
    .string "I know every single move that\n"
    .string "POKÉMON learn as they grow.\p"
    .string "Do you want me to teach a move to\n"
    .string "a POKÉMON of yours?$"

gText_TutorWhichMon::
    .string "Which POKÉMON needs tutoring?$"

gText_TeachWhichMove::
    .string "Which move should I teach?$"

gText_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKÉMON.$"

gText_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

gText_ComeBackAgain::
    .string "Come see me again if you need\n"
    .string "another move taught to a POKÉMON.$"
    