CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "This department store\n"
    .string "has everything!$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for POKéMON\n"
    .string "held items.\p"
    .string "MAGNET ups the power\n"
    .string "of ELECTRIC moves.\p"
    .string "CHARCOAL ups the power\n"
    .string "of FIRE moves.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"

