# 1 "data/maps/PalletTown_NewHome1_1F/scripts.pory"

# 2 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
PalletTown_NewHome1_1F_MapScripts::
# 3 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.byte 0
# 4 "data/maps/PalletTown_NewHome1_1F/scripts.pory"

# 5 "data/maps/PalletTown_NewHome1_1F/scripts.pory"

# 6 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
PalletTown_NewHome1_1F_EventScript_Lass::
# 7 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 4 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 8 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	lock
# 9 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 5 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 10 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	faceplayer
# 11 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 6 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 12 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	msgbox PalletTown_NewHome1_1F_EventScript_Lass_Text_0
# 13 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 7 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 14 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	release
# 15 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	end
# 16 "data/maps/PalletTown_NewHome1_1F/scripts.pory"

# 17 "data/maps/PalletTown_NewHome1_1F/scripts.pory"

# 18 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
PalletTown_NewHome1_1F_EventScript_Lass_Text_0:
# 19 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 6 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
# 20 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.string "KANTO has grown quite a bit in recent\n"
# 21 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.string "years. You'll find new developments in\l"
# 22 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.string "many cities around the region just\l"
# 23 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.string "like here in Pallet Town.$"

PalletTown_NewHome1_1F_Man::
# 27 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	lock
# 28 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	faceplayer
# 29 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	msgbox PalletTown_NewHome1_1F_Man_Text_0
# 30 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	release
	end


PalletTown_NewHome1_1F_Man_Text_0:
# 29 "data/maps/PalletTown_NewHome1_1F/scripts.pory"
	.string "POKéMON from the JOHTO region have\nbeen seen all throughout KANTO.\pYou might even find some in the\nRoutes up ahead.$"
